---
- name: Compile PBS source code
  hosts: all
  become: yes
  tasks:
  - name: Running autogen.sh
    command: ./autogen.sh
    args:
      chdir: /pbs
  - name: Running configure
    command: ./configure
    args:
      chdir: /pbs
  - name: Running make
    command: make dist
    args:
      chdir: /pbs

