---
- name: To copy tar file to rpmbuild/SOURCES
  hosts: all
  become: yes
  tasks:
  - find: paths="/pbs" patterns="pbspro*tar.gz"
    register: file_to_copy
  - debug:
     #var: file_to_copy.files[0].path
     #var: file_to_copy.files
     
  - copy: 
      src: "{{ item.path }}"
      dest: /home/ajay/rpmbuild/SOURCES
      remote_src: yes
    with_items: 
      - "{{ file_to_copy.files }}"

  - copy:
      src: /pbs/pbspro.spec
      dest: /home/ajay/rpmbuild/SPECS
      remote_src: yes
