---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: ajtest
        location: eastus

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: ajtest
        name: testvn001
        address_prefixes: "192.168.1.0/24"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: ajtest
        name: subnet001
        address_prefix: "192.168.1.0/24"
        virtual_network: testvn001

    - name: Create public ip
      azure_rm_publicipaddress:
        resource_group: ajtest
        allocation_method: Dynamic
        name: publicip001

    - name: Create Security Group
      azure_rm_securitygroup:
        resource_group: ajtest
        name: secgroup001
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ajtest
        name: ajtestnic
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: publicip001
        security_group: secgroup001

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: ajtest
        name: ajvm001
        vm_size: Standard_DS1_v2
        admin_username: ajay
        admin_password: C@tty1234567890
        network_interfaces: ajtestnic
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
