---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: ajtest1
        location: eastus

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: ajtest1
        name: testvn001
        address_prefixes: "192.168.1.0/24"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: ajtest1
        name: subnet001
        address_prefix: "192.168.1.0/24"
        virtual_network: testvn001
###########################################################
    - name: Create public ip
      azure_rm_publicipaddress:
        resource_group: ajtest1
        allocation_method: Dynamic
        name: "{{ item }}"
      with_items:
        - ajpubip001
        - ajpubip002


###################################################3

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ajtest1
        name: ajtestnic1
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: publicip001


    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ajtest1
        name: ajtestnic2
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: publicip002

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ajtest1
        name: ajtestnic3
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: publicip003

##############################################################
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: ajtest1
        name: ajvm001
        vm_size: Standard_DS1_v2
        admin_username: ajay
        admin_password: C@tty1234567890
        network_interfaces: ajtestnic1
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest


    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: ajtest1
        name: ajvm002
        vm_size: Standard_DS1_v2
        admin_username: ajay
        admin_password: C@tty1234567890
        network_interfaces: ajtestnic2
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: ajtest1
        name: ajvm003
        vm_size: Standard_DS1_v2
        ssh_password_enabled: no
        admin_username: ajay
        ssh_public_keys:
          - path: /home/ajay/.ssh/authorized_keys
            key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDV+KiWVAyczYItZqhiclmxLBfCJq2jprbKol+98Ilp3w+HuxIlIJBy+8Aqz5eCA7KiCWeX/wmhjwmypzGTY9F05Ic97/6mY+8471aEtc4d9+9hCuYRjW//+YUl1/fn2GeOaZ1cy68VMGE6Fxx2xAIMcEE1QQ5kxwfAjU65rezbjtAWDolJHWUnWQX5IkibIdWjUKUJAemM4eri8/XHpI2RvCQlS6GUpHyYKECo7hBW6iy1cl6mgPYoqp5+9U8oGAvcuCiWJKlMtVvX3wXXS6flt15aNZ10Dz4rFzvJDYVqJgR1zd+pRkG6Yh6fnSbLeebFXx/j/+PeGKz65hIt6R/ vagrant@centos7.ajay.com
        network_interfaces: ajtestnic3
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
