- name: Initialize Kubernetes Cluster
  hosts: node01

  - name: Init
    command: kubeadm init --apiserver-advertise-address=172.42.42.101 --podnetwork-cidr=10.244.0.0/16


  - name: Ensire /home/vagrant/.kube/config exists
    file: /home/vagrant/.kube/config state=directory

  - name: Copy kube config
    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant

  - name: Deploy flannel network
    command: kubectl apply -f https://raw.githubusercontent.com/justmeandopensource/kubernetes/master/vagrant-provisioning/kube-flannel.yml
