- name: Initialize Kubernetes Cluster
  hosts: node01
  tasks:
  #  - name: Init
    #  become: yes
    #  command: "kubeadm init --apiserver-advertise-address=172.42.42.101 --pod-network-cidr=10.244.0.0/16"

    - name: Ensure config exists
      file:
        path: /home/vagrant/.kube
        state: directory

    - name: Copy kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        remote_src: yes

    - name: Deploy flannel network
      command: kubectl apply -f https://raw.githubusercontent.com/justmeandopensource/kubernetes/master/vagrant-provisioning/kube-flannel.yml
