version: '3'
services:
  PS:
    privileged: true
    image: ibmcom/spectrum-symphony
    volumes:
      - /data/cluster1:/shared
    networks:
      - symnet
    environment:
      - LICENSE=accept
    ports:
      - "8443"
      - "8543"
      - "8050"
  PS_COM:
    privileged: true
    image: ibmcom/spectrum-symphony
    networks:
      - symnet
    environment:
      - LICENSE=accept
      - HOST_ROLE=COMPUTE
networks:
  symnet:
